import { useEffect, useState } from 'react';
import Header from './components/Header.jsx';
import CustomerTable from './components/CustomerTable.jsx';
import { Hero, IntroSections, Thobes, Manufacturing, QualityGallery, Testimonials } from './components/SiteSections.jsx';

export default function App() { const [language, setLanguage] = useState(() => localStorage.getItem('masharLanguage') || 'en'); useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; localStorage.setItem('masharLanguage', language); }, [language]); return <><Header language={language} onLanguageChange={() => setLanguage(language === 'en' ? 'ar' : 'en')} /><main><Hero /><IntroSections /><Thobes /><Manufacturing /><QualityGallery /><Testimonials /><CustomerTable /><Stores /><Contact /></main><Footer /></>; }

function Stores() { return <section className="stores section" id="stores"><div className="container"><div className="section-head"><div><p className="eyebrow">OUR SHOWROOMS</p><h2>Find a Mashar Store Near You</h2></div><p className="head-copy">Visit our showrooms and experience the quality, craftsmanship and comfort of Mashar thobes in person.</p></div><div className="stores-grid">{['Al Khobar', 'Al Rabi', 'Hittin', 'Al Wurud', 'Al Rawdah', 'Al Naseem', 'Jeddah'].map((store, index) => <article className="store-card" key={store}><div className="store-number">{String(index + 1).padStart(2, '0')}</div><div className="store-info"><h3>{store}</h3><div className="store-detail"><span className="store-icon">📍</span><p>Saudi Arabia</p></div><div className="store-detail"><span className="store-icon">☎</span><p><a className="phone-number" href="tel:+966500000000">+966 50 000 0000</a></p></div><a href="https://www.google.com/maps" target="_blank" rel="noreferrer" className="store-map-btn">GET DIRECTIONS →</a></div></article>)}</div></div></section>; }

function Contact() { return <section className="contact section" id="contact"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow">CONTACT MASHAR</p><h2>Let's make your next collection.</h2><p>Share your required styles, quantities, fabric preferences and delivery requirements. We will review your enquiry and get back to you.</p><div className="contact-list"><p><strong>Location</strong><span>Hail, Kingdom of Saudi Arabia</span></p><p><strong>Phone</strong><span><a href="tel:+966500000000">+966 50 000 0000</a></span></p><p><strong>Email</strong><span>sales@mashar.sa</span></p></div></div><form className="contact-form" onSubmit={event => { event.preventDefault(); event.currentTarget.reset(); window.alert('Thank you. Your enquiry has been received.'); }}><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input type="email" name="email" required placeholder="Email address" /></label><label>Mobile<input name="phone" placeholder="+966..." /></label><label>Requirement<select name="requirement"><option value="">Select an option</option><option>Classic Thobes</option><option>Premium Thobes</option><option>Embroidery Thobes</option><option>Winterwear Thobes</option></select></label><label>Message<textarea name="message" rows="6" placeholder="Tell us about your requirement" /></label><button type="submit">Send Enquiry →</button></form></div></section>; }

function Footer() { return <footer className="footer"><div className="container footer-top"><div className="footer-links">{['about', 'whymashar', 'thobes', 'manufacturing', 'quality', 'gallery', 'stores', 'customers', 'contact'].map(id => <a href={`#${id}`} key={id}>{id}</a>)}</div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Mashar Men's Factory. All rights reserved.</span><button type="button" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>Back to top ↑</button></div></footer>; }